// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mfoshcaprxurhknxaujw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1mb3NoY2Fwcnh1cmhrbnhhdWp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2OTgyMTAsImV4cCI6MjA3MTI3NDIxMH0.rQ0rLocl6G-VgbLRRGCHgzT1YkghhUJcn40dOg7daqg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});