// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://csgwbpvywltpmqkvjxmt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzZ3dicHZ5d2x0cG1xa3ZqeG10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MzU2OTcsImV4cCI6MjA3MDUxMTY5N30.QQ5ak6OKhFiNW5PtgeSu1IjxvylJ5LG9jA0ECfPJouY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});